package com.smartcampus.api.model;

/**
 * Represents a single data reading captured by a sensor at a moment in time.
 *
 * Readings form the historical log for a sensor.
 * They are stored as a sub-resource under /api/v1/sensors/{sensorId}/readings
 *
 * When a new reading is POSTed, the parent Sensor's currentValue is automatically
 * updated to match this reading's value — keeping the API data consistent.
 *
 * Example JSON:
 * {
 *   "id": "a3f1c2b4-...",
 *   "timestamp": 1713178800000,
 *   "value": 23.7
 * }
 */
public class SensorReading {

    /**
     * Unique event ID — a UUID string.
     * Generated by the server automatically on POST (client doesn't need to provide it).
     */
    private String id;

    /**
     * Epoch time in milliseconds when the reading was captured.
     * If not provided by the client, the server sets it to the current time.
     */
    private long timestamp;

    /** The actual measured value — temperature, CO2 ppm, occupancy count, etc. */
    private double value;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /** Default no-arg constructor required by Jackson */
    public SensorReading() {}

    public SensorReading(String id, long timestamp, double value) {
        this.id = id;
        this.timestamp = timestamp;
        this.value = value;
    }

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public double getValue() {
        return value;
    }

    public void setValue(double value) {
        this.value = value;
    }
}
